owner = "bnjbvr"
dry_run = false

[[repos]]
name = "octotest"
ci_passed_label = "ci-passed"
reviewed_label = "reviewed"
trivial_review_label = "trivial"
comment_requests_change = true
required_statuses = []
