owner = "davidpdrsn"
dry_run = false

[[repos]]
name = "octotest"
ci_passed_label = "ci-passed"
reviewed_label = "reviewed"
skip_review_label = "trivial"
needs_description_label = "needs-description"
block_merge_label = "block-merge"
comment_requests_change = true
react_to_comments = true
required_statuses = []
automerge_grace_period = 60
